### ISSUE TITLE
Secure Connection Failed

### ISSUE THREAD

**Issue by ShangwenWang** [tech-srl/slm-code-generation#3]
Dear authors,
At this time, we have no access to the [online demo](https://anycodegen.org/).
It seems that there is a secure problem. Would you please have a look at it?

**Comment by urialon** [comment]
Hi,
Thank you for your interest in SLM.

This is odd because it doesn't seem to me that there is a problem.
I can access the website both through my home network and my mobile network.

1. Do you have another network/ISP that you can try accessing the demo with? (mobile, home, school, work, etc?)
2. Can you access the website on this URL: [https://code2code-d5c6c.firebaseapp.com/](https://code2code-d5c6c.firebaseapp.com/)

Uri

**Comment by ShangwenWang** [comment]
Dear author, 
I have two networks, one is my laptop and another is my work computer. Neither of them can access the website. As for the URL you provided, I still cannot access it.
Besides, when I try to query the API of the trained model now, it returns me the message "Internal server error".
So odd.

**Comment by urialon** [comment]
1. Are you in China right now?
2. Can you access our other websites: [https://code2vec.org/](https://code2vec.org/) and [https://code2seq.org/](https://code2seq.org/) ?

**Comment by ShangwenWang** [comment]
Yes, I am in China now.
But I can access these two webpages with no problem

**Comment by urialon** [comment]
Is Google or other Google services blocked for you in China?

**Comment by ShangwenWang** [comment]
I think that is not the problem.
I can access Google homepage right now.

**Comment by urialon** [comment]
There is a [website that checks whether a website is blocked in China](https://www.comparitech.com/privacy-security-tools/blockedinchina/#:~:text=How%20can%20I%20access%20blocked,is%20to%20use%20a%20VPN.&text=By%20installing%20a%20VPN%20app,and%20freely%20access%20the%20web.), and it says that our online demo is **OK**:
![image](https://user-images.githubusercontent.com/15002544/90407977-da9f6800-e0af-11ea-9eaa-737094f4213b.png)

By the way, so far you have tried [anycodegen.org](anycodegen.org) . Can you check [anycodegen.com](anycodegen.com) ?

**Comment by ShangwenWang** [comment]
It's so odd. I ask one of my friends to have a try and he can access.
It seems that my network has some problems.
Sorry for disturbing you.

**Comment by urialon** [comment]
No problem.
