### ISSUE TITLE
Can I download the model?

### ISSUE THREAD

**Issue by Marken23** [tech-srl/slm-code-generation#4]

**Comment by urialon** [comment]
Hi @Marken23 ,
Thank you for your interest in our model.
We are working on it. 

Currently, we only released the API that allows querying the trained model, see here: https://github.com/tech-srl/slm-code-generation#querying-the-trained-model

I promise to let you know in this thread once we release the code and the trained model.
Best,
Uri

**Comment by Marken23** [comment]
Thanks for your efforts!

**Comment by forest520** [comment]
Any plan to release to Tensorflow code? Thanks!

**Comment by urialon** [comment]
Yes, definitely. We're working on it.

**Comment by monperrus** [comment]
Hi Uri, we would also need the Tensorflow code in our research project. Thanks! --Martin

**Comment by urialon** [comment]
Of course, I know :-)

**Comment by monperrus** [comment]
Nice :+1:  For us to plan our experiments, would you have an ETA? Thanks Uri.
