### ISSUE TITLE
Embeddings 

### ISSUE THREAD

**Issue by MadRajib** [tech-srl/slm-code-generation#6]
Hello Uri Alon，
After reading through the paper, I had some queries.

1. Embeddings that are using for Encoding AST paths are they learned while training or they are pre-learned matrixes?

**Comment by urialon** [comment]
Hi @MadRajib ,
Thank you for your interest in our paper!

In our implementation, all embedding are learned, including both "subtoken embedding" (like `my`,`list`,`value`) and "node embedding" (like `ForStatement`, `ArrayAccess`, `MethodCall`).

Best,
Uri
