### ISSUE TITLE
About the baseline of Java any-code completion

### ISSUE THREAD

**Issue by ShangwenWang** [tech-srl/slm-code-generation#7]
Dear authors, 
  Thanks for your work!
  Your work is really great since there is no any-code completion tool before. I wonder would you release the baseline you designed to compare with AnyCodeGen on Java language (e.g., the retrained code2seq). I find building and retraining them would cause lots of time and energy. Thanks.

**Comment by ShangwenWang** [comment]
I mean can I query the trained code2seq like [this](https://github.com/tech-srl/slm-code-generation#querying-the-trained-model)
Really need your help. Thanks

**Comment by urialon** [comment]
Hi,
This baseline was a prototype adaptation of code2seq to SLM by taking the [data of SLM](https://github.com/tech-srl/slm-code-generation#datasets) and converting it to the [code2seq format](https://github.com/tech-srl/code2seq#extending-to-other-languages).

The `head_paths` from SLM are the paths that we used in code2seq. 
The target sequence (that should be predicted) in code2seq is the `linearized_tree` in SLM or `target_seq` (depending on whether you wish to predict the target as a sequence of tokens or a linearized tree).

Best,
Uri

**Comment by ShangwenWang** [comment]
Dear @urialon 
Thanks for your reply. I wonder will you provide a query link to the adaptation just like you have done for AnyCodeGen.
It is time consuming if retraining the model, not to mention any technical problem I might meet.
